### ISSUE TITLE
ATmega328p@8MHz can't do 115200 baud

### ISSUE THREAD

**Issue by Tiogaplanet** [sparkfun/MiP_ProMini-Pack#11]
The MiP's UART  port only works at 115200 and the ATmega328p@8MHz can't read long strings from the MiP at 115200.  It works OK for one or two bytes then the data starts getting corrupted.  This board should be built around the ATmega328p@16MHz and 5V.

I've purchased the Arduino Pro Mini 5V/16MHz to continue developing the SparkFun MiP Arduino library.  The library should be pretty portable between the MiP ProMini Pack and the Arduino Pro Mini 5V/16MHz.

**Comment by adamgreen** [comment]
Now testing a new 5V/16MHz version of the MiP ProMini Pack design from [over here](https://github.com/adamgreen/MiP_ProMini-Pack#readme) with a new more feature complete [Arduino library](https://github.com/adamgreen/MiP_ProMini-Pack/tree/master/Arduino/MiP_ProMini_Pack_Library).

**Comment by Tiogaplanet** [comment]
Long overdue to close this.  Confirmed ATmega328p@8MHz not suited to 115200bps.  Switch to 5V/16MHz version solves the problem.
